name: deploy
  on:
    push:
      branches:
      - master
    pull_request:
      branches:
      - master
  uses: peaceiris/actions-gh-pages@v4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
